name: Build OSW-OS (Ubuntu, all models)

on:
  workflow_dispatch:
  push:
    paths_ignore: '["*.md", "**/scripts/screen_capture/**"]'
  pull_request:
    branches: [ master, develop ]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.2.0
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  Find-packages:
    runs-on: ubuntu-latest
    needs: check_skip
    if: ${{ needs.check_skip.outputs.should_skip != 'true' }}
    steps:      
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - id: get-languages
        run: echo "::set-output name=languages_matrix::$(./.github/setMatrix.sh --get-languages)"
      - id: get-default-languages
        run: echo "::set-output name=default_languages_matrix::$(./.github/setMatrix.sh --default-lang)"
      - id: get-models
        run: echo "::set-output name=models_matrix::$(./.github/setMatrix.sh --get-models)"
    outputs:
      languages_matrix: ${{ steps.get-languages.outputs.languages_matrix }}
      default_languages_matrix: ${{ steps.get-default-languages.outputs.default_languages_matrix }}
      models_matrix: ${{ steps.get-models.outputs.models_matrix }}
  build-OSW:
    needs: Find-packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(needs.Find-packages.outputs.languages_matrix) }}
        defaultLanguage: ${{ fromJson(needs.Find-packages.outputs.default_languages_matrix) }}
        model: ${{ fromJson(needs.Find-packages.outputs.models_matrix) }}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install swig
      run: sudo apt-get update && sudo apt-get -y install swig
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: python -m pip install --upgrade pip && pip install --upgrade platformio
    - name: Rename config
      run: mv include/config.h.example include/config.h
    - uses: dorny/paths-filter@v2.2.1
      id: filter
      with:
        filters: |
          i8n:
            - 'include/locales/'
    - name: Compile model ${{ matrix.model }}
      run: |
        if [[ ${{ steps.filter.outputs.i8n }} == "true" ]]; then
          python3 .github/buildEverything.py -l ${{ matrix.language }} -m ${{ matrix.model }}
        else
          python3 .github/buildEverything.py -l ${{ matrix.defaultLanguage }} -m ${{ matrix.model }}
        fi    
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmwares
        path: |
          *.bin
