name: OSW-OS-test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master, develop ]

jobs:
  find-languages:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo "::set-output name=languages_matrix::$(curl https://api.github.com/repos/open-smartwatch/open-smartwatch-os/contents/include/locales | jq -c '[.[].name[0:-2]]')"
    outputs:
      languages_matrix: ${{ steps.set-matrix.outputs.languages_matrix }}
  build_linux:
    needs: find-languages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(needs.find-languages.outputs.languages_matrix) }}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install swig
      run: sudo apt-get update && sudo apt-get -y install swig
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: python -m pip install --upgrade pip && pip install --upgrade platformio
    - name: Rename config
      run: mv include/config.h.example include/config.h
    - name: Compile language ${{ matrix.language }} model
      run: python3 .github/buildEverything.py -l ${{ matrix.language }} 
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmwares
        path: |
          *.bin
