name: Build OSW Emulator (Ubuntu)

on:
  workflow_dispatch:
  push:
    paths_ignore: '["**/*.md", "**/scripts/screen_capture/**"]'
  pull_request:
    branches: [ master, develop ]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.2.0
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  build-EMULATOR:
    runs-on: ubuntu-22.04
    needs: check_skip
    if: ${{ needs.check_skip.outputs.should_skip != 'true' }}
    steps:  
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Update packages
      run: sudo apt-get update && sudo apt-get upgrade -y
    - name: Install packages
      run: sudo apt-get -y install gcc g++ cmake libsdl2-dev libsdl2-image-dev
    - name: Create build directory
      run: mkdir build
    - name: CMake (debug)
      run: cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: Make
      run: cd build && make -j $(nproc)
    - name: Test
      run: cd build && make test
